[entropy]
enabled = true
threshold = 3.8
min_length = 24

[[exclusions]]
pattern = "**/node_modules/**"
policy = "Ignore"

[[exclusions]]
pattern = "**/test-fixtures/**"
policy = "ScanButAllow"

[[exclusions]]
pattern = "docs/examples/**"
policy = "ScanButWarn"

[[patterns]]
name = "stripe-key"
pattern = '''(?i)stripe_(secret|live)_key\s*=\s*['"]?(sk_(live|test)_[a-zA-Z0-9]{24})'''
description = "Stripe Secret Key"

[[patterns]]
name = "jwt-token" 
pattern = '''(?i)eyJ[a-zA-Z0-9_-]{5,}\.eyJ[a-zA-Z0-9_-]{5,}\.[a-zA-Z0-9_-]{10,}'''
description = "JWT Token"