name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - run: cargo test --all-features

  release-linux-windows:
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@cross
      - run: cross build --release --target x86_64-unknown-linux-gnu
      - run: cross build --release --target x86_64-pc-windows-gnu
      - uses: actions/upload-artifact@v4
        with:
          name: linux-windows-binaries
          path: |
            target/x86_64-unknown-linux-gnu/release/redflag
            target/x86_64-pc-windows-gnu/release/redflag.exe

  release-macos:
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      # Install Rust toolchain with macOS target
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          targets: x86_64-apple-darwin

      - run: rustup target add x86_64-apple-darwin
      # Build for macOS
      - run: cargo build --release --target x86_64-apple-darwin

      # Upload macOS binary as an artifact
      - uses: actions/upload-artifact@v4
        with:
          name: macos-binary
          path: target/x86_64-apple-darwin/release/redflag

  create-release:
    needs: [release-linux-windows, release-macos]
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write  # Add write permissions for releases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: linux-windows-binaries
          path: target/x86_64-unknown-linux-gnu/release
      - uses: actions/download-artifact@v4
        with:
          name: macos-binary
          path: target/x86_64-apple-darwin/release
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            target/x86_64-unknown-linux-gnu/release/redflag
            target/x86_64-unknown-linux-gnu/release/redflag.exe
            target/x86_64-apple-darwin/release/redflag